"""after test cleanup

Revision ID: 092f72324af4
Revises: fb792fa67892
Create Date: 2026-02-20 10:44:30.467209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092f72324af4'
down_revision: Union[str, Sequence[str], None] = 'fb792fa67892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_type', sa.String(length=100), nullable=False))
    op.add_column('products', sa.Column('product_stock', sa.Integer(), nullable=False))
    op.drop_column('products', 'product_description')
    op.drop_column('products', 'product_quantity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('product_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('products', 'product_stock')
    op.drop_column('products', 'product_type')
    # ### end Alembic commands ###
